### ISSUE TITLE
numpy array instance referenced in python data structure causes serialization of the latter to fail

### ISSUE THREAD

**Issue by lebedov** [uqfoundation/dill#100]
Using dill 0.2.2 with numpy 1.9.2 and Python 2.7.9, the following runs without any problems:

```
import dill
import numpy
x = numpy.ones((2,2))
data = {}
data['x'] = x
dill.dumps(data)
```

However, if I try serializing `x` immediately before `data`, Python raises an AssertionError when attempting the second serialization:

```
import dill
import numpy
x = numpy.ones((2,2))
data = {}
data['x'] = x
dill.dumps(x)
dill.dumps(data)
```

The same problem occurs if `data` is a list and I append `x` to it.

The problem only seems to occur when `x` is a numpy array; I wasn't able to reproduce the error when I set `x` to a variety of other data types (e.g., lists, dicts, Pandas DataFrame instances, ...). Any idea why this is occurring?

**Comment by matsjoyce** [comment]
Its python 2.7 only, by the looks of it:
```py
>>> import dill
>>> import numpy
>>> x = numpy.ones((2,2))
>>> data = {}
>>> data['x'] = x
>>> dill.dumps(x)
Nu: ((2, 2), float64)
F2: <function _create_array at 0x7ffb6e0b7ed8>
B2: <built-in function _reconstruct>
T4: <type 'numpy.ndarray'>
T4: <type 'numpy.dtype'>
'\x80\x02cdill.dill\n_create_array\nq\x00(cnumpy.core.multiarray\n_reconstruct\nq\x01cnumpy\nndarray\nq\x02K\x00\x85q\x03U\x01bq\x04\x87q\x05(K\x01K\x02K\x02\x86q\x06cnumpy\ndtype\nq\x07U\x02f8q\x08K\x00K\x01\x87q\tRq\n(K\x03U\x01<q\x0bNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x0cb\x89U \x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?q\rtq\x0eNtq\x0fRq\x10.'
>>> dill.dumps(data)
D2: <dict object at 0x7ffb6e053c58>
Nu: ((2, 2), float64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dill/dill.py", line 194, in dumps
    dump(obj, file, protocol, byref, fmode)#, strictio)
  File "dill/dill.py", line 184, in dump
    pik.dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "dill/dill.py", line 678, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/lib/python2.7/pickle.py", line 649, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/lib/python2.7/pickle.py", line 686, in _batch_setitems
    save(v)
  File "/usr/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "dill/dill.py", line 181, in save_numpy_array
    pik.save_reduce(_create_array, (f, args, state, npdict), obj=obj)
  File "/usr/lib/python2.7/pickle.py", line 405, in save_reduce
    self.memoize(obj)
  File "/usr/lib/python2.7/pickle.py", line 244, in memoize
    assert id(obj) not in self.memo
AssertionError
>>>
```

@mmckerns I think its got something to do with your `hack to catch subclassed numpy array instances`:
```py
    if NumpyArrayType and ndarrayinstance(obj):
        @register(type(obj))
        def save_numpy_array(pickler, obj):
            log.info("Nu: (%s, %s)" % (obj.shape,obj.dtype))
            npdict = getattr(obj, '__dict__', None)
            f, args, state = obj.__reduce__()
            pik.save_reduce(_create_array, (f, args, state, npdict), obj=obj)
            return
```
The `Nu` code is from this bit, and it would make sense, as its only active if the the primary dumped object is a `ndarray`. As its 2.7 only, it might be related to the python 2-3 difference that showed up in #96.

**Comment by mmckerns** [comment]
@matsjoyce: I suspect you are right.  Looking at python3.3, `Nu` is not called, it's `B1` which finds the `_reconstruct` function, as expected.

```
Python 3.3.6 (default, Feb 26 2015, 04:22:26) 
[GCC 4.2.1 Compatible Apple Clang 4.1 ((tags/Apple/clang-421.11.66))] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> dill.detect.trace(True)
>>> import numpy
>>> x = numpy.ones((2,2))
>>> data = {}
>>> data['x'] = x
>>> dill.dumps(data)
D2: <dict object at 0x1018d2cb0>
B1: <built-in function _reconstruct>
F2: <function _get_attr at 0x10259c200>
M2: <module 'numpy.core.multiarray' from '/opt/local/Library/Frameworks/Python.framework/Versions/3.3/lib/python3.3/site-packages/numpy/core/multiarray.so'>
F2: <function _import_module at 0x10259c320>
T4: <class 'numpy.ndarray'>
T4: <class 'numpy.dtype'>
b'\x80\x03}q\x00X\x01\x00\x00\x00xq\x01cdill.dill\n_get_attr\nq\x02cdill.dill\n_import_module\nq\x03X\x15\x00\x00\x00numpy.core.multiarrayq\x04\x85q\x05Rq\x06X\x0c\x00\x00\x00_reconstructq\x07\x86q\x08Rq\tcnumpy\nndarray\nq\nK\x00\x85q\x0bC\x01bq\x0c\x87q\rRq\x0e(K\x01K\x02K\x02\x86q\x0fcnumpy\ndtype\nq\x10X\x02\x00\x00\x00f8q\x11K\x00K\x01\x87q\x12Rq\x13(K\x03X\x01\x00\x00\x00<q\x14NNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x15b\x89C \x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?q\x16tq\x17bs.'
```
...and going back to 2.5, it finds `_reconstruct` via `B2`, so it looks like it's only 2.7.
```
Python 2.5.6 (r256:88840, Nov 18 2012, 05:37:10) 
[GCC 4.2.1 Compatible Apple Clang 4.1 ((tags/Apple/clang-421.11.66))] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Module readline not available.
>>> import dill 
>>> import numpy
>>> dill.detect.trace(True)
>>> x = numpy.ones((2,2))
>>> data = {}
>>> data['x'] = x
>>> dill.dumps(data)
D2: <dict object at 0x7f804bb8a920>
B2: <built-in function _reconstruct>
T4: <type 'numpy.ndarray'>
T4: <type 'numpy.dtype'>
'\x80\x02}q\x00U\x01xq\x01cnumpy.core.multiarray\n_reconstruct\nq\x02cnumpy\nndarray\nq\x03K\x00\x85q\x04U\x01bq\x05\x87q\x06Rq\x07(K\x01K\x02K\x02\x86q\x08cnumpy\ndtype\nq\tU\x02f8q\nK\x00K\x01\x87q\x0bRq\x0c(K\x03U\x01<q\rNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x0eb\x89U \x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?q\x0ftq\x10bs.'
```

**Comment by mmckerns** [comment]
Should be fixed with ac45fb17c857c09089de2d9d0cf9782d255f82cf

**Comment by lebedov** [comment]
The problem still seems to occur with 6ba3fa9 when used with Python 2.7.9.

**Comment by matsjoyce** [comment]
Same here. Same traceback, too.

**Comment by mmckerns** [comment]
I'm not seeing it.

```
Python 2.7.9 (default, Dec 11 2014, 01:21:43) 
[GCC 4.2.1 Compatible Apple Clang 4.1 ((tags/Apple/clang-421.11.66))] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> dill.detect.trace(True)
>>> import numpy
>>> x = numpy.ones((2,2))
>>> data = {}
>>> data['x'] = x
>>> 
>>> dill.dumps(data)
D2: <dict object at 0x1004f34b0>
B2: <built-in function _reconstruct>
T4: <type 'numpy.ndarray'>
T4: <type 'numpy.dtype'>
'\x80\x02}q\x00U\x01xq\x01cnumpy.core.multiarray\n_reconstruct\nq\x02cnumpy\nndarray\nq\x03K\x00\x85q\x04U\x01bq\x05\x87q\x06Rq\x07(K\x01K\x02K\x02\x86q\x08cnumpy\ndtype\nq\tU\x02f8q\nK\x00K\x01\x87q\x0bRq\x0c(K\x03U\x01<q\rNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x0eb\x89U \x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\xf0?q\x0ftq\x10bs.'
>>> numpy.__version__
'1.9.2'
```

**Comment by matsjoyce** [comment]
@mmckerns You've missed the `dill.dumps(x)` before `dill.dumps(data)`.

**Comment by mmckerns** [comment]
@matsjoyce: Ah, thanks. I'm seeing the error now… and it's also in the entire `2.x` series.  It looks like a conflicting `register` of types.

**Comment by mmckerns** [comment]
Ok, squished it this time in f08db33e5d2c4cb66ab7f78f817b9b99c1aef159.

**Comment by lebedov** [comment]
Confirmed. Thanks, guys.
