### ISSUE TITLE
Recursion error with partial and self references

### ISSUE THREAD

**Issue by aleneum** [uqfoundation/dill#234]
Since the dill upgrade from 0.2.6 to 0.2.7, we experience recursion errors (pytransitions/transitions#236 ; stack trace below). This seems to be related to the usage of `functool.partial` and the assignment to object properties of `self`. This code works with 0.2.6 but not with 0.2.7:

```python
import dill as pickle
from functools import partial


def get_trigger(model):
    pass


class Machine(object):

    def __init__(self):
        self.child = Model()
        # raises RuntimeError
        self.trigger = partial(get_trigger, self)
        # does not work either
        self.child.trigger = partial(get_trigger, self.child)


class Model(object):
    pass

m = Machine()
dump = pickle.dumps(m)
```

Error output:
```python
Traceback (most recent call last):
  File "/Users/alneuman/Workspace/transitions/test_dill.py", line 17, in <module>
    dump = pickle.dumps(m)
  File "/usr/local/lib/python2.7/site-packages/dill/dill.py", line 279, in dumps
    dump(obj, file, protocol, byref, fmode, recurse)#, strictio)
  File "/usr/local/lib/python2.7/site-packages/dill/dill.py", line 272, in dump
    pik.dump(obj)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python2.7/site-packages/dill/dill.py", line 869, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 692, in _batch_setitems
    save(v)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
...
RuntimeError: maximum recursion depth exceeded in cmp
```

**Comment by mmckerns** [comment]
I see this error too.  Ok, I'll dig in.  May be related to #232.

If I add `pickle.detect.trace(True)` with `dill-0.2.6`, I get:

```
T2: <class '__main__.Machine'>
F2: <function _create_type at 0x10774c2a8>
# F2
T1: <type 'type'>
F2: <function _load_type at 0x10774c230>
# F2
# T1
T1: <type 'object'>
# T1
D2: <dict object at 0x10782a280>
F1: <function __init__ at 0x1078735f0>
F2: <function _create_function at 0x10774c320>
# F2
Co: <code object __init__ at 0x1073770b0, file "Test_partial.py", line 12>
T1: <type 'code'>
# T1
# Co
D1: <dict object at 0x107322168>
# D1
D2: <dict object at 0x10782f5c8>
# D2
# F1
# D2
# T2
D2: <dict object at 0x1073c8910>
Fu: <functools.partial object at 0x1078663c0>
F2: <function _create_ftype at 0x10774c398>
# F2
T1: <type 'functools.partial'>
# T1
F1: <function get_trigger at 0x107873500>
Co: <code object get_trigger at 0x1075aab30, file "Test_partial.py", line 6>
# Co
D1: <dict object at 0x107322168>
# D1
D2: <dict object at 0x10782fa28>
# D2
# F1
D2: <dict object at 0x10783da28>
# D2
# Fu
T2: <class '__main__.Model'>
D2: <dict object at 0x10782a910>
# D2
# T2
D2: <dict object at 0x10782a4b0>
Fu: <functools.partial object at 0x107866418>
D2: <dict object at 0x10782f4b0>
# D2
# Fu
# D2
# D2
```

**Comment by mmckerns** [comment]
The released version gives:
```
T2: <class '__main__.Machine'>
F2: <function _create_type at 0x103887488>
# F2
T1: <type 'type'>
F2: <function _load_type at 0x103887410>
# F2
# T1
T1: <type 'object'>
# T1
D2: <dict object at 0x103965280>
F1: <function __init__ at 0x1039ae8c0>
F2: <function _create_function at 0x103887500>
# F2
Co: <code object __init__ at 0x1034af0b0, file "Test_partial.py", line 12>
T1: <type 'code'>
# T1
# Co
D1: <dict object at 0x10345a168>
# D1
D2: <dict object at 0x1039695c8>
# D2
# F1
# D2
# T2
D2: <dict object at 0x103500910>
Fu: <functools.partial object at 0x10399d3c0>
F2: <function _create_ftype at 0x103887578>
# F2
T1: <type 'functools.partial'>
F2: <function _load_type at 0x103887410>
# F2
# T1
F1: <function get_trigger at 0x1039ae7d0>
F2: <function _create_function at 0x103887500>
# F2
Co: <code object get_trigger at 0x1036e2b30, file "Test_partial.py", line 6>
T1: <type 'code'>
# T1
# Co
D1: <dict object at 0x10345a168>
# D1
D2: <dict object at 0x103969a28>
# D2
# F1
T2: <class '__main__.Machine'>
F2: <function _create_type at 0x103887488>
# F2
T1: <type 'type'>
F2: <function _load_type at 0x103887410>
# F2
# T1
T1: <type 'object'>
# T1
D2: <dict object at 0x10396f7f8>
F1: <function __init__ at 0x1039ae8c0>
F2: <function _create_function at 0x103887500>
# F2
Co: <code object __init__ at 0x1034af0b0, file "Test_partial.py", line 12>
T1: <type 'code'>
# T1
# Co
D1: <dict object at 0x10345a168>
# D1
D2: <dict object at 0x1039695c8>
# D2
# F1
# D2
# T2

...[repeating]...

D2: <dict object at 0x103500910>
Fu: <functools.partial object at 0x10399d3c0>
F2: <function _create_ftype at 0x103887578>
# F2
T1: <type 'functools.partial'>
F2: <function _load_type at 0x103887410>
# F2
# T1
F1: <function get_trigger at 0x1039ae7d0>
F2: <function _create_function at 0x103887500>
# F2
Co: <code object get_trigger at 0x1036e2b30, file "Test_partial.py", line 6>
T1: <type 'code'>
# T1
# Co
D1: <dict object at 0x10345a168>
# D1
D2: <dict object at 0x103969a28>
# D2
# F1
T2: <class '__main__.Machine'>
F2: <function _create_type at 0x103887488>
# F2
Traceback (most recent call last):
...
```
and into the traceback as reported.

**Comment by mmckerns** [comment]
should be fixed. let me know if that's not the case.

**Comment by aleneum** [comment]
Works like a charm. Thank you for the quick fix and in general for sharing `dill` with the community! Much appreciated and best regards 🎉 !

**Comment by aleneum** [comment]
Damn, the test above still fails with Python 3.3.5.

I tested the following versions

|Python|Status|
|:------:|:-----:|
|2.7.13|✔|
|**3.3.5**|✘|
|3.4.5|✔|
|3.5.3|✔|
|3.6.0|✔|

**Comment by mmckerns** [comment]
Yes, I saw it fails for 3.1-3.3, and at least 2.7.9 and earlier.  Not sure about 2.7.10-2.7.12.  It's not quite as urgent if it's just older versions like 3.3.

**Comment by mmckerns** [comment]
@aleneum: how does this work for you?

I think I've squashed all the cases except recurse=True for 3.3 and older in cases where a `partial` is in the class method.

**Comment by aleneum** [comment]
The test above works now for Python 3.3. However, member functions and inheritance still causes the recursion issue though. This works for Python 2.7.11 but not for Python 3.3.5 (deinstalled and reinstalled dill in both cases):

```python
import dill as pickle
from functools import partial


class Machine(object):

    def __init__(self):
        self.go = partial(self.member, self)

    def member(self, model):
        pass


class SubMachine(Machine):

    def __init__(self):
        super(SubMachine, self).__init__()


m = SubMachine()
dump = pickle.dumps(m)
```

**Comment by mmckerns** [comment]
Moving this to a new ticket, see #236.
